export const invoiceModel = {
  documentNumber: "1001",
  documentCounter: 1001,
  documentType: "Invoice",
  documentYear: new Date().getFullYear().toString().slice(-2),
  documentSuffix: "",

  customer: "",
  customerEmail: "",
  contactPersonPhone: "",
  billingAddress: "",

  businessName: "",
  businessEmail: "",
  businessAddress: "",

  invoiceDate: "",
  dueDate: "",

  currency: {
    code: "PKR",
    symbol: "Rs",
  },

  country: "Australia",
  businessNumber: "",

  subtotal: 0,
  itemDiscountsTotal: 0,
  discountType: "percent",
  discount: "",
  discountAmount: 0,
  taxType: "percent",
  tax: "",
  total: 0,
  balanceDue: 0,
  notes: "",
  phoneNo: "",
  companyPhone: "",
  companyWebsite: "",
  companyLocation: "",
  signatureName: "",
  signatureTitle: "",
  thankYouText: "",
  createdAt: new Date().toISOString(),
  payment: "",
  contractType: "Fixed",
  milestoneNumber: 1,
  isDraft: false,
  draftType: null,
};